version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev